from numpy import *
a=array([1,2,4,-5,8],int)
b=array([4,6,2,0,-3],int)
print(a+b)
print(a[3])
for i in a:
    print(pow(i,3))
print(a+3)
print(b/2)
d=linspace(1,10,7)
print(d)
print(id(d))
f=arange(1,10)
print(f)
d=logspace(1,10,4)
print(d)
d=zeros(5)
print(d)
print(concatenate([f,d]))